version: '3'
services:
  micro:
    container_name: micro
    # image: snowplow/snowplow-micro:1.7.2-distroless
    image: snowplow/snowplow-micro:1.7.2
    volumes:
      - ./config:/config
    restart: always
    ports:
      - '9090:9090'
    command: '--collector-config /config/micro.conf --iglu /config/iglu.json'

  iglu:
    image: halverneus/static-file-server
    volumes:
      - ./iglu:/web
    ports:
      - '9091:9091'
