name = "${PROJECT_NAME}"
workers_dev = true
main = "src/server.ts"

# Enter your account id
# This can be found at https://dash.cloudflare.com/ --> Workers & Pages
#  --> Overview, then in the right sidebar
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Run the `wrangler kv:namespace create sonicjs` command and copy the id below
# Run the `wrangler kv:namespace create sonicjs --preview` command and copy the preview_id below
# Only update the preview_id and id, leave the binding name as "KVDATA"
kv_namespaces = [
  { binding = "KVDATA", id = "${PROJECT_KV_ID}" }
]

# Run the `wrangler d1 create sonicjs` command and copy the id below
[[d1_databases]]
binding = "D1DATA"
database_name = "${PROJECT_D1_NAME}"
database_id = "${PROJECT_D1_ID}"

# Using Cloudflare R2 (similar to AWS S3) is only necessary if you plan to use SonicJs to manage file assets
# Run the `wrangler r2 bucket create sonicjs` command and uncomment the section below
[[r2_buckets]]
binding = 'R2STORAGE' 
bucket_name = "${PROJECT_R2_NAME}"

vars = { ENVIRONMENT = "production" }

# [env.development]
# vars = { ENVIRONMENT = "development" }