name = "${PROJECT_NAME}"
compatibility_date = "2024-02-23"

compatibility_flags = ["nodejs_compat"]

account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "KVDATA"
id = "${PROJECT_KV_ID}"

# SQLite DB
[[d1_databases]]
binding = "D1DATA"
database_name = "${PROJECT_D1_NAME}"
database_id = "${PROJECT_D1_ID}"
preview_database_id = "D1DATA" # Required for Pages local development

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = 'R2STORAGE' 
bucket_name = "${PROJECT_R2_NAME}"